### ISSUE TITLE
how to enable debug or verbose 

### ISSUE THREAD

**Issue by angelxmoreno** [Paul-Lazunko/evodove#1]
I have docker containers running my nodeJS + Evodove instance. From my node server, I can reach the evodove server and I can confirm the port is open. However, my node app refuses to connect. How do I debug this?

**Comment by Paul-Lazunko** [comment]
Hi. it would be great if you could provide more details or show the code, in this case we would quickly solve this problem.  so far I do not rule out local docker network issues or running the apps with different parameters

**Comment by angelxmoreno** [comment]
My compose file:
```xml
version: '2'
services:
  node:
    container_name: ${APP_PREFIX}-node
    image: node:16.8-alpine3.14
    command: yarn dev
    working_dir: /app
    volumes:
      - ../:/app
    ports:
      - ${NODE_PORT}:${PORT}
    links:
      - mysql
      - redis
      - evodove
  evodove:
    container_name: ${APP_PREFIX}-evodove
    build:
        context: ./evodove
    restart: on-failure
    environment:
      - EVODOVE_WORKERS_COUNT=${EVODOVE_WORKERS_COUNT}
      - EVODOVE_STORE_RESPONSE_MS=${EVODOVE_STORE_RESPONSE_MS}
      - EVODOVE_SECURE_KEY=${EVODOVE_SECURE_KEY}
    ports:
      - ${EVODOVE_SERVER_PORT}:45678
    volumes:
      - ./data/evodove:/app/data:delegated
  mysql:
    container_name: ${APP_PREFIX}-mariadb
    image: mariadb:10.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${APP_PREFIX}
      - MYSQL_USER=${APP_PREFIX}
      - MYSQL_PASSWORD=${APP_PREFIX}
      - MYSQL_DATABASE=${APP_PREFIX}
    volumes:
      - ./data/mysql:/var/lib/mysql:delegated
    ports:
      - ${MYSQL_PORT}:3306
  redis:
    container_name: ${APP_PREFIX}-redis
    image: redis:alpine
    command: redis-server --requirepass ${APP_PREFIX}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data/redis:/var/lib/redis:delegated
```

Evodove `Dockerfile`:
```sh
FROM node:12.16.1-alpine

WORKDIR /app

ENV EVODOVE_SERVER_PORT=45678
ENV EVODOVE_DATA_VOLUME=/app/data
ENV EVODOVE_WORKERS_COUNT ;
ENV EVODOVE_STORE_RESPONSE_MS ;
ENV EVODOVE_SECURE_KEY ;

COPY package.json ./package.json
COPY server.js ./server.js

RUN npm install

EXPOSE 45678

CMD [ "npm", "start" ]
```

`package.json` for the Evodove container:
```json
{
    "name": "evodove-server",
    "version": "1.0.0",
    "main": "server.js",
    "license": "MIT",
    "scripts": {
        "start": "node server.js"
    },
    "dependencies": {
        "evodove": "^2.0.6"
    }
}
```

`server.js` for the Evodove container:
```js
const { Evodove } = require('evodove');

const evodove = new Evodove();
console.info('Starting Evodove');
evodove.start();
```

my client connect setup:
```
import { EvodoveClient } from 'evodove';

const clientOptions = {
    host: 'evodove',
    port: 45678,
    secureKey: 'mySecureKey',
    reconnectInterval: 1000,
    doReconnectOnClose: true,
    requestTimeout: 10000,
};

const client = new EvodoveClient(clientOptions);

const connectClient = async () => {
    try {
        await client.connect();
    } catch (e) {
        console.error('Unable to connect to EvodoveClient', clientOptions);
        return;
    }
    await client.subscribe('foo', outputParams => {
        console.info(`CHANNEL: foo: `, outputParams);
    });
};

export default { connectClient };
```

**Comment by Paul-Lazunko** [comment]
Thanks.
So I think that problem was caused by invalid secure property in the client options:

const clientOptions = {
    host: 'evodove',
    port: 45678,
    secureKey: 'mySecureKey',
    reconnectInterval: 1000,
    doReconnectOnClose: true,
    requestTimeout: 10000,
};

Just change **clientOptions. secureKey** parameter's value to **process.env.EVODOVE_SECURE_KEY**

I hope that it will help. Will be waiting for your response.

**Comment by Paul-Lazunko** [comment]
Additionally you have to provide the same environment variables for your Node.js app as you added for evodove instance - to be sure that it has the same configuration

**Comment by Paul-Lazunko** [comment]
You can use as an example

https://github.com/Paul-Lazunko/evodove-docker-example

**Comment by angelxmoreno** [comment]
@Paul-Lazunko the only noticeable difference between the sample compose file and mine is that you are setting up a network. I'll create a repo to replicate my findings.

**Comment by angelxmoreno** [comment]
and of course, doing the setup from scratch worked 🤦 
https://github.com/angelxmoreno/evodove-compose-example
What I did do differently was not use TS. That would be the next step. But I suspect my issue was definitely env related. Thanks!
